import Fastify from 'fastify';
import { keccak256, toHex } from 'viem';
import {
  ANVIL_RPC,
  DEV,
  EscrowClient,
  EscrowState,
  RegistryClient,
  balanceOf,
  publicClient,
  walletClient,
} from '@hire402/sdk';

/**
 * THE CODER AGENT (Phase 2) — a thin variant of the genesis researcher:
 * same self-registration, same escrowed trust rails, different unit and
 * price. Sells `task:code` at 1.50 USDC. Demonstrates that adding a new
 * worker agent to the economy is a copy + unit change.
 */

const RPC = process.env.HIRE402_RPC ?? ANVIL_RPC;
const ESCROW = process.env.ESCROW_ADDRESS;
const USDC = process.env.USDC_ADDRESS;
const REGISTRY_URL = process.env.REGISTRY_URL ?? 'http://127.0.0.1:4010';
const PORT = Number(process.env.PORT ?? 4120);
const PRICE = BigInt(process.env.TASK_PRICE ?? '1500000'); // 1.50 USDC
const CODER_KEY = process.env.CODER_KEY ?? DEV.buyer; // distinct worker keys arrive via env in real deployments

interface TaskState {
  taskId: string;
  status: 'working' | 'submitted' | 'released' | 'rejected';
  escrowId: bigint;
  index: bigint;
  buyer?: string;
  description: string;
  startTx?: string;
  submitTx?: string;
  claimTx?: string;
  attestation?: string;
  result?: string;
  error?: string;
}

const tasks = new Map<string, TaskState>();
let pc: ReturnType<typeof publicClient>;
let wc: ReturnType<typeof walletClient>;
let escrow: EscrowClient;
let registry: RegistryClient;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function doCode(description: string): string {
  return [
    `// module: ${description.slice(0, 40)}`,
    'export function entrypoint(): string {',
    "  return 'generated by the coder agent — proof of deliverable';",
    '}',
  ].join('\n');
}

async function workOnTask(task: TaskState): Promise<void> {
  try {
    let core: Awaited<ReturnType<EscrowClient['core']>> | undefined;
    let milestone: Awaited<ReturnType<EscrowClient['milestone']>> | undefined;
    for (let attempt = 0; attempt < 20; attempt++) {
      try {
        const c = await escrow.core(task.escrowId);
        const m = await escrow.milestone(task.escrowId, task.index);
        if (Number(c.state) === EscrowState.Funded || Number(c.state) === EscrowState.Active) {
          core = c;
          milestone = m;
          break;
        }
      } catch {
        /* not visible yet */
      }
      await sleep(1500);
    }
    if (!core || !milestone) {
      task.status = 'rejected';
      task.error = 'escrow never became visible/funded on chain';
      return;
    }
    if (core.seller.toLowerCase() !== escrow.account.toLowerCase()) {
      task.status = 'rejected';
      task.error = 'escrow seller is not me';
      return;
    }
    if (Number(core.state) === EscrowState.Funded) {
      task.startTx = await escrow.start(task.escrowId);
    }

    task.status = 'working';
    await sleep(1200);

    const result = doCode(task.description);
    const attestation = `ipfs://${keccak256(toHex(result)).slice(2)}`;
    task.result = result;
    task.attestation = attestation;
    task.submitTx = await escrow.submit(task.escrowId, task.index, attestation);
    task.status = 'submitted';
    console.log(`[coder  ] task ${task.taskId} submitted (${attestation})`);

    const challenge = BigInt(core.challengeSeconds);
    let attempts = 0;
    for (;;) {
      const m = await escrow.milestone(task.escrowId, task.index);
      if (Number(m.status) === 3) break;
      if (Number(m.status) === 5 || Number(m.status) === 4) {
        task.status = 'rejected';
        task.error = `milestone ended in status ${m.status}`;
        return;
      }
      const now = (await pc.getBlock()).timestamp;
      if (BigInt(m.submittedAt) + challenge < BigInt(now)) {
        try {
          task.claimTx = await escrow.claimTimeout(task.escrowId, task.index);
          break;
        } catch (e) {
          attempts += 1;
          if (attempts > 10) throw e;
          await sleep(2000);
          continue;
        }
      }
      await sleep(2000);
    }
    task.status = 'released';
    console.log(`[coder  ] task ${task.taskId} paid — earned ${PRICE} (6dp)`);
  } catch (e) {
    task.status = 'rejected';
    task.error = String(e);
    console.error(`[coder  ] task ${task.taskId} failed:`, e);
  }
}

async function main() {
  if (!ESCROW || !USDC) {
    console.error('ESCROW_ADDRESS and USDC_ADDRESS are required');
    process.exit(1);
  }
  pc = publicClient(RPC);
  wc = walletClient(CODER_KEY as `0x${string}`, RPC);
  escrow = new EscrowClient(pc, wc, ESCROW as `0x${string}`, USDC as `0x${string}`);
  registry = new RegistryClient(REGISTRY_URL, wc, pc);

  const me = escrow.account;
  console.log(`[coder  ] I am ${me} — starting USDC balance: ${await balanceOf(pc, USDC as `0x${string}`, me)}`);

  // Spawned agents carry lineage (spec §9): the child records its parent.
  const parent = process.env.AGENT_PARENT;
  await registry.post('/v1/agents', {
    address: me,
    agentCardUrl: `http://127.0.0.1:${PORT}/.well-known/agent-card.json`,
    x402: { chains: ['eip155:31337'], assets: ['USDC'] },
    ...(parent ? { lineage: { parent } } : {}),
  });
  await registry.post('/v1/listings', {
    unit: 'task:code',
    pricing: { model: 'milestones', escrow: ESCROW, milestones: [{ amount: PRICE.toString(), deadlineHours: 24 }] },
    sla: { p50Seconds: 5, p99Seconds: 120, uptime30d: 1.0 },
  });
  console.log(`[coder  ] listed task:code @ ${PRICE} (6dp USDC)`);

  const app = Fastify({ logger: false });
  app.get('/healthz', async () => ({ ok: true, service: 'hire402-coder' }));
  app.get('/wallet', async () => ({ address: me, usdcBalance: (await balanceOf(pc, USDC as `0x${string}`, me)).toString() }));
  app.post('/tasks', async (req, reply) => {
    const body = (req.body ?? {}) as { escrowId?: string | number; milestoneIndex?: number; buyer?: string; description?: string };
    const escrowId = BigInt(body.escrowId ?? 0);
    if (escrowId === 0n || !body.description) {
      return reply.code(400).send({ error: 'escrowId and description required' });
    }
    const taskId = `code_${Date.now().toString(36)}`;
    const task: TaskState = {
      taskId, status: 'working', escrowId, index: BigInt(body.milestoneIndex ?? 0),
      buyer: body.buyer ?? 'unknown', description: body.description,
    };
    tasks.set(taskId, task);
    void workOnTask(task);
    return reply.code(202).send({ taskId, status: task.status });
  });
  app.get('/tasks/:id', async (req, reply) => {
    const { id } = req.params as { id: string };
    const t = tasks.get(id);
    if (!t) return reply.code(404).send({ error: 'task not found' });
    return {
      taskId: t.taskId, status: t.status, escrowId: t.escrowId.toString(),
      startTx: t.startTx, submitTx: t.submitTx, claimTx: t.claimTx,
      attestation: t.attestation, result: t.result, detail: t.error,
    };
  });

  await app.listen({ port: PORT, host: '0.0.0.0' });
  console.log(`[coder  ] listening on :${PORT} — ready to build for the market`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});

